# Generated by Django 5.2.13 on 2026-04-19 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_device_is_deleted_devicehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
