# Generated by Django 5.2.13 on 2026-04-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_ticket_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancereport',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
