# Generated by Django 5.2.13 on 2026-04-23 08:24

import core_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_maintenancereport_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='devices/', validators=[core_app.validators.validate_file_size, core_app.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('HEAD_TECHNICIAN', 'Technicien Principal'), ('TECHNICIAN', 'Technicien IT'), ('USER', 'Utilisateur Simple')], max_length=20, unique=True),
        ),
    ]
