# Generated by Django 5.2.13 on 2026-04-23 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_alter_device_image_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name__in': ['TECHNICIAN', 'HEAD_TECHNICIAN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenancereport',
            name='technician',
            field=models.ForeignKey(limit_choices_to={'role__name__in': ['TECHNICIAN', 'HEAD_TECHNICIAN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
