# Generated by Django 5.2.13 on 2026-04-23 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_ticket_assigned_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='core_app.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
